name: testing main-branch
# run test on develop branch
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install
        run:  npm install
      - name: Cypress test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build   
          start: npm run start
          component: true
    